version: '3.7'

services:
  database_uniCash:
    image: postgres
    container_name: database_uniCash
    hostname: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=uniCash
      - POSTGRES_DB=uniCash
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: uniCash
    depends_on: 
      - database_uniCash
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local